# Generated by Django 5.0.1 on 2024-01-04 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Thème',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Forum')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.CharField(max_length=3000, verbose_name='Description')),
                ('creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('forum_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.theme', verbose_name='Thème')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Sujet')),
                ('slug', models.SlugField(blank=True)),
                ('contacts', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Contacts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='Forum')),
            ],
            options={
                'verbose_name': 'Conversation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='Forum')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='ForumAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Vignette')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('joined', models.DateField(auto_now_add=True, verbose_name='Rejoins le')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sous catégorie')),
                ('slug', models.SlugField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='forum.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Sous catégorie',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True)),
                ('closed', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('pin', models.BooleanField(default=False, verbose_name='Epinglé')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Activité récente')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Sujet',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('personal', models.BooleanField(default=False, verbose_name='Personnel')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('update_counter', models.IntegerField(default=0, verbose_name='Nombre de maj')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.conversation', verbose_name='Messagerie Personnel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forumaccount', verbose_name='Auteur')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.topic', verbose_name='Sujet')),
            ],
            options={
                'ordering': ['creation'],
            },
        ),
    ]
