# Generated by Django 5.0 on 2023-12-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumaccount',
            options={'verbose_name': 'Compte'},
        ),
        migrations.AlterField(
            model_name='forumaccount',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Vignette'),
        ),
    ]
