# Generated by Django 5.0 on 2023-12-14 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subcategory'),
        ),
    ]
