# Generated by Django 5.0 on 2023-12-13 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.theme', verbose_name='Thème'),
        ),
    ]
