# Generated by Django 5.0.1 on 2024-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_index_subcategory_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['index'], 'verbose_name': 'Sous catégorie'},
        ),
        migrations.AddField(
            model_name='forum',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Logo', verbose_name='Logo'),
        ),
    ]
