# Generated by Django 5.0 on 2023-12-17 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-creation']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-creation'], 'verbose_name': 'Sujet'},
        ),
        migrations.AlterField(
            model_name='message',
            name='personal_messaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.personalmessaging', verbose_name='Messagerie Personnel'),
        ),
    ]
