# Generated by Django 5.0.1 on 2024-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_badge_forumaccount_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0, verbose_name="J'aime"),
        ),
    ]
