# Generated by Django 5.0.1 on 2024-01-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
    ]
