# Generated by Django 5.0 on 2023-12-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
