# Generated by Django 5.0 on 2023-12-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du Forum'),
        ),
    ]
