# Generated by Django 5.0 on 2023-12-20 21:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_message_options_message_update_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Message'),
        ),
    ]
