# Generated by Django 5.0 on 2023-12-20 21:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Message'),
        ),
    ]
