# Generated by Django 5.0 on 2023-12-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
