# Generated by Django 5.0 on 2023-12-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumaccount',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Vignette'),
        ),
    ]
