# Generated by Django 5.0 on 2023-12-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_rename_personalmessaging_conversation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation'},
        ),
    ]
