# Generated by Django 5.0 on 2023-12-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_alter_topic_options_topic_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Description'),
        ),
    ]
